name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Aquí corregimos el nombre del autor (ArtemSerebrennkov)
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11

      - name: Upload artifact
        # Aquí usamos la versión v4 (la v2 que tenías está obsoleta)
        uses: actions/upload-artifact@v4
        with:
          name: MiAppKivy
          path: bin/*.apk
          

